# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be8eff0a89ebf1bf715a5a8bf03df7b1740bfa8529c4ffd8d80bad90808fc6b519cfd62f8872caf9e6ee69c08ef18b23329cff8260e3d07dab88a5f7bc20c8c

test:
  secret_key_base: c0014761413eceae0c632cc1d9f973b565e27455bbae2f6f4fb05678f2a8e8097f6161fa247907f441cb96613293e25f63c206af2b792305c0d63f2f7e83c5a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
